### ISSUE TITLE
gplay loading error 

### ISSUE THREAD

**Issue by adamsolivagant** [joseyose/assetLoader#12]
not able to load the asset to gplay. any suggestions? @joseyose

**Comment by joseyose** [comment]
@adamsolivagant which OS are you on? Are you able to load the UI at all or is it just the asset loading that is not working?

**Comment by adamsolivagant** [comment]
I'm on linux and the file loader is working fine, but when i select the file and try to load it in gplay nothing happens when i hit the load button.

**Comment by joseyose** [comment]
gotcha! and are you sure you have houdini on your `PATH`? 
If you just run `gplay`  directly on your terminal does it load an instance of `gplay`? 
If it doesn't make sure to add Houdini to your `PATH`

**Comment by adamsolivagant** [comment]
yeah houdini is in my path and wierdly can't access gplay from terminal, but running the executable directly from bin folder works.
also i just checked that same issue is happening in windows.

**Comment by joseyose** [comment]
Are you referring to the same issue of gplay not loading from the terminal? 

I've just tested on linux and windows again and the application works, but if you are unable to load `gplay` directly from your terminal then your `houdini/bin` path is not set correctly. 

You need to be able to load gplay directly from your terminal. This application is launching a gplay process every time you want to load a mesh.

**Comment by joseyose** [comment]
Closing this
